#!/bin/bash
set -e

KEY=80B93EA53DC484D1D86E672B40972A700CD3618F

dpkg-scanpackages --multiversion . > Packages
gzip -k -f Packages

apt-ftparchive release . > Release
gpg --default-key $KEY -abs -o - Release > Release.gpg
gpg --default-key $KEY --clearsign -o - Release > InRelease
